import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'uz_UZ': {
          "log_in_to_your_account": "Shaxsiy hisobga kirish",
          "email": "Elektrom pochta",
          "password": "Parol",
          "login": "Kirish",
          "enter_your_email": "Elektron pochtangizni kiriting.",
          "enter_your_password": "Parolingizni kiriting.",
          "groups": "Guruhlar",
          "add_student": "Talaba qo'shish",
          "enter_name_of_the_student": "Talaba ismini kiriting",
          "enter_surname_of_the_student": "Talaba familiyasini kiriting.",
          "name": "Ism",
          "surname": "Familiya",
          "save": "Saqlash",
          "successfully_added": "talabalar safiga muvaffaqqiyatli qo'shildi!",
          "group_name": "Guruh nomi",
          "specific_room": "Biriktirilgan xona",
          "lesson_time": "Dars jadvali",
          "enter_group_name": "Guruh nomini kiriting",
          "enter_room_name": "Biriktirilgan xonani kiriting",
          "enter_lesson_time": "Dars jadvalini kiriting",
          "created_successfully": " guruhi muvaffaqqiyatli yaratildi!",
          "list_of_students": "Talabalar ro'yxati",
          "add_group": "Guruh qo'shish",
          "add_teacher": "Mentor qo'shish",
          "teacher_added": " jamoa safiga muvaffaqqiyatli qo'shildi!",
          "list_of_groups": "Guruhlari ro'yxati:",
          "add_lesson": "Dars qo'shish",
          "cancel": "Bekor qilish",
        },
        "ru_RU": {
          "log_in_to_your_account": "Войти в личный кабинет",
          "email": "Электронная почта",
          "password": "Пароль",
          "login": "Вход",
          "enter_your_email": "Введите адрес электронной почты.",
          "enter_your_password": "Введите ваш пароль.",
          "groups": "Группы",
          "add_student": "Добавить студента",
          "enter_name_of_the_student": "Введите имя студента",
          "enter_surname_of_the_student": "Введите фамилию студента.",
          "name": "Имя",
          "surname": "Фамилия",
          "save": "Сохранять",
          "successfully_added": "успешно влился в ряды студентов!",
          "group_name": "Имя группы",
          "specific_room": "Класс",
          "lesson_time": "Расписание занятий",
          "enter_group_name": "Введите название групп",
          "enter_room_name": "Введите класса",
          "enter_lesson_time": "Введите расписание занятий",
          "created_successfully": " создано успешно!",
          "list_of_students": "Список студентов",
          "add_group": "Добавить группу",
          "add_teacher": "Добавить наставника",
          "teacher_added": " успешно присоединился к команде!",
          "list_of_groups": "Список групп:",
          "add_lesson": "Добавить урок",
          "cancel": "Отменить",
        },
        "en_EN": {
          "log_in_to_your_account": "Login to your account",
          "email": "Email",
          "password": "Parol",
          "login": "Login",
          "enter_your_email": "Enter your email.",
          "enter_your_password": "Enter your password.",
          "groups": "Groups",
          "add_student": "Add student",
          "enter_name_of_the_student": "Enter name of the student",
          "enter_surname_of_the_student": "Enter surname of the student.",
          "name": "Name",
          "surname": "Surname",
          "save": "Save",
          "successfully_added": "successfully joined the ranks of students!",
          "group_name": "Group name",
          "specific_room": "Room",
          "lesson_time": "Class schedule",
          "enter_group_name": "Enter name of the group",
          "enter_room_name": "Enter name of the class room",
          "enter_lesson_time": "Enter class schedule",
          "created_successfully": " created successfully!",
          "list_of_students": "List of students",
          "add_group": "Add group",
          "add_teacher": "Add mentor",
          "teacher_added": " successfully joined the team!",
          "list_of_groups": "List of groups:",
          "add_lesson": "Add lesson",
          "cancel": "Cancel"
        }
      };
}
